# Generated by Django 4.1.5 on 2023-05-07 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternatif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simbol', models.CharField(max_length=50, unique=True)),
                ('nik', models.IntegerField()),
                ('nama_alternatif', models.CharField(max_length=50, unique=True)),
                ('alamat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simbol', models.CharField(max_length=50)),
                ('nama_kriteria', models.CharField(max_length=50)),
                ('bobot', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='SubKriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sub_kriteria', models.CharField(max_length=50)),
                ('nilai_sub_kriteria', models.IntegerField()),
                ('kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SPK.kriteria')),
            ],
        ),
        migrations.CreateModel(
            name='Penilaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anak_sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_anak_sekolah', to='SPK.subkriteria')),
                ('bumil_dan_bunsui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_bumil_dan_bunsui', to='SPK.subkriteria')),
                ('kondisi_rumah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_kondisi_rumah', to='SPK.subkriteria')),
                ('lansia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_lansia', to='SPK.subkriteria')),
                ('nama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_nama', to='SPK.alternatif', to_field='nama_alternatif')),
                ('penghasilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_penghasilan', to='SPK.subkriteria')),
                ('simbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_simbol', to='SPK.alternatif', to_field='simbol')),
            ],
        ),
    ]
