# Generated by Django 4.1.5 on 2023-05-09 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SPK', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penilaian',
            name='simbol',
        ),
    ]
