# Generated by Django 4.1.5 on 2023-05-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPK', '0002_remove_penilaian_simbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kriteria',
            name='bobot',
            field=models.FloatField(),
        ),
    ]
