# Generated by Django 4.1.5 on 2023-05-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPK', '0006_alter_rengking_alternatif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rengking',
            name='alternatif',
            field=models.CharField(max_length=50),
        ),
    ]
