# Generated by Django 4.1.5 on 2023-05-12 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SPK', '0007_alter_rengking_alternatif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rengking',
            name='alternatif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SPK.alternatif'),
        ),
    ]
