# Generated by Django 4.1.5 on 2023-05-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPK', '0008_alter_rengking_alternatif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rengking',
            name='total_nilai',
            field=models.FloatField(null=True),
        ),
    ]
